repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: ruff
      language: system
      types: [python]

    - id: ruff_format
      name: ruff_format
      entry: ruff
      args: ["format", "."]
      language: system
      types: [python]
