services:
    app:
        container_name: youtube_scanner_app
        image: youtube_scanner_app
        command: uv run python -m app
        volumes:
            - ${APP_DATA}/logs:${LOG__DIR}
        environment:
            LOG__DIR: $LOG__DIR
            LOG__CONFIG: $LOG__CONFIG

            BOT__TOKEN: $BOT__TOKEN
            BOT__ADMIN_IDS: $BOT__ADMIN_IDS

            REDIS__USE: $REDIS__USE
            REDIS__URL: $REDIS__URL
            REDIS__QUEUE: $REDIS__QUEUE

            STORAGE_FILE: $STORAGE_FILE

            SCAN_SCHEDULE: $SCAN_SCHEDULE
            NOTIFY_SCHEDULE: $NOTIFY_SCHEDULE

            WITHOUT_SENDING: $WITHOUT_SENDING
            PARSE_TAGS: $PARSE_TAGS

            DATABASE_URL: $DATABASE_URL
            SEND_DELAY: $SEND_DELAY

            APP_TZ: $APP_TZ
            TZ: $TZ
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_started

    redis:
        container_name: redis
        image: redis
        command: redis-server --save "" --appendonly no

    database:
        container_name: postgres
        image: postgres:14.1-alpine
        volumes:
            - ${APP_DATA}/init_db:/docker-entrypoint-initdb.d/
            - ${APP_DATA}/database_data:/var/lib/postgresql/data
        environment:
            PGUSER: $PGUSER
            PGPASSWORD: $PGPASSWORD
            POSTGRES_PASSWORD: $PGPASSWORD
            PGDATABASE: $PGDATABASE
            PGHOST: $PGHOST
            PGPORT: $PGPORT
        healthcheck:
              test: ["CMD-SHELL", "pg_isready"]
              interval: 5s
              timeout: 5s
              retries: 5