[project]
name = "youtubescannerbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "aiogram~=3.15.0",
    "alembic~=1.10.2",
    "apscheduler~=3.10.1",
    "asyncpg~=0.27.0",
    "beautifulsoup4~=4.11.1",
    "colorama~=0.4.4",
    "colorlog~=6.7.0",
    "lxml~=4.9.1",
    "pydantic~=2.9.2",
    "pydantic-settings~=2.7.0",
    "python-dateutil~=2.8.2",
    "python-dotenv~=1.0.0",
    "redis~=4.5.5",
    "sqlalchemy~=2.0.23",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pylint>=3.3.7",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.0.0",
    "ruff==0.1.5",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-colorama>=0.4.15.20240311",
    "types-python-dateutil>=2.9.0.20250516",
    "types-redis>=4.6.0.20241004",
]



[tool.ruff]
exclude = [
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "venv",
    ".venv",
    ".env",
    ".idea",
    ".vscode",
    "logs",
    "photos",
]
line-length = 79
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = [
    # pycodestyle
    #"E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    #"SIM",
    # isort
    "I",
]
ignore = []

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["F401"]


[tool.mypy]
strict = false
exclude = [
    "^venv/.*$",
    "^migrations/.*$",
    "^tests/.*$",
    "^scripts/.*$",
]
plugins = [
  "pydantic.mypy",
]

[[tool.mypy.overrides]]
module = "aiogram.*,apscheduler.*,pydantic_settings.*"
ignore_missing_imports = true


[tool.pytest.ini_options]
testpaths = [
    "tests",
]
python_files = "test_*.py"
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
log_cli = true
log_cli_level = "DEBUG"

[tool.pylint.messages_control]
disable = [
  "C0114",
  "C0115",
  "C0116",
  "R0903",
  "R0913",
  "R0914",
  "R0917",
]
[tool.pylint.master]
ignore = [
   ".venv",
   "migrations",
   "tests",
   "scripts",
]
