"""initial
Revision ID: 447f9219817f
Revises: Create Date: 2023-03-29 20:33:24.525720
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "447f9219817f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "TelegramChats",
        sa.Column("original_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("is_creator", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("original_id"),
    )
    op.create_table(
        "YouTubeChannels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_id", sa.String(), nullable=False),
        sa.Column("canonical_base_url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original_id"),
    )
    op.create_table(
        "TelegramThreads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_id", sa.Integer(), nullable=False),
        sa.Column("original_chat_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["original_chat_id"],
            ["TelegramChats.original_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "original_id", "original_chat_id", name="unique_thread"
        ),
    )
    op.create_table(
        "YouTubeChannelTags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["YouTubeChannels.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["Tags.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "YouTubeVideos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("style", sa.String(), nullable=False),
        sa.Column("time_ago", sa.String(), nullable=False),
        sa.Column("scan_time", sa.DateTime(), nullable=False),
        sa.Column("creation_time", sa.DateTime(), nullable=False),
        sa.Column("live_24_7", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["YouTubeChannels.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original_id"),
    )
    op.create_table(
        "Forwarding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("youtube_channel_id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sa.Integer(), nullable=False),
        sa.Column("telegram_thread_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telegram_chat_id"],
            ["TelegramChats.original_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["telegram_thread_id"],
            ["TelegramThreads.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["youtube_channel_id"],
            ["YouTubeChannels.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "youtube_channel_id",
            "telegram_chat_id",
            "telegram_thread_id",
            name="unique_forwarding",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Forwarding")
    op.drop_table("YouTubeVideos")
    op.drop_table("YouTubeChannelTags")
    op.drop_table("TelegramThreads")
    op.drop_table("YouTubeChannels")
    op.drop_table("TelegramChats")
    op.drop_table("Tags")
    # ### end Alembic commands ###
