"""Add ForwardedVideo table

Revision ID: f79abfe7f733
Revises: 0f4a9f4a0595
Create Date: 2024-10-16 12:22:33.794091

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f79abfe7f733"
down_revision = "0f4a9f4a0595"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ForwardedVideos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("chat_original_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_original_id"],
            ["TelegramChats.original_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["TelegramThreads.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["YouTubeVideos.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "video_id",
            "chat_original_id",
            "thread_id",
            name="unique_forwarded_video",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ForwardedVideos")
    # ### end Alembic commands ###
